### PR TITLE
fix: add go omitempty json tag

### PR DESCRIPTION
**Pull request by Souvikns**
## Description

This PR is adding a new option for `GO_COMMON_PRESET` for generating `omitempty` parameter. 

## Checklist
- [x] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully locally.(`npm run test`).

### CODE REVIEW

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
I dont think this should be having it's own option, it's required for the json tags to correctly work IMO 🤔 

Why would you like to have it as an option @Souvikns?

**Comment by Souvikns** [comment]
It needs `addJsonTag` to work, I added an option thinking that if anyone does not need it, if anyone wants to have empty data while Marshaling, they can do it. Just didn't wanted to force the `omitempty` tag on the user.

**Comment by jonaslagoni** [comment]
The problem as I see it with adding it as an option is that it currently (by default) creates incorrect JSON Data as soon as you have an optional property or null type. To me this is a bug rather then a missing feature 🤔

**Review by jonaslagoni — CHANGES_REQUESTED** [review]
Got some snapshots that are not happy :v:

**Review by jonaslagoni — APPROVED** [review]
👍

**Pull request merged**
